[project]
name = "kokoro-manim-voiceover"
version = "0.1.0"
description = "Library for generating voiceover in manim using Kokoro-82M model"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kokoro-onnx>=0.3.6",
    "manim>=0.19.0",
    "manim-voiceover>=0.3.7",
    "soundfile>=0.13.0",
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "setuptools>=75.8.0"
]
authors = [
    {name = "Nadeem Akhtar Khan", email = "nadeemak755@gmail.com"}
]
license = {text = "MIT"}
keywords = ["manim", "voiceover", "text-to-speech", "kokoro", "animation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
]

[project.urls]
Homepage = "https://github.com/xposed73/kokoro-manim-voiceover"
Repository = "https://github.com/xposed73/kokoro-manim-voiceover"
Issues = "https://github.com/xposed73/kokoro-manim-voiceover/issues"

[build-system]
requires = ["setuptools>=75.8.0", "wheel"]
build-backend = "setuptools.build_meta"
